FROM node:18-alpine

# Install dependencies only when needed
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json package-lock.json* ./
RUN npm ci

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

ENV PORT 3000
ENV NODE_ENV development

# Start the application in development mode
CMD ["npm", "run", "dev"]
